Link base with dl on unix-like systems
${CMAKE_DL_LIBS} evaluates to dl 
This is needed for dladdr which is called mrpt::system::getCallStackBackTrace()

This should fix the build error with the minimal build with the error
../../lib/libmrpt-base.so.1.9.9: undefined reference to `dladdr'