mrpt_opengl: Export opengl dependency
Packages depending on mrpt_opengl need to have opengl headers
available. Therefore, we change opengl dependency from build_depend to
build_export_depend.

Without this change, building e.g. mrpt_imgui leads to the following
error:

    In file included from /build/mrpt3-release-release-humble-mrpt_imgui-3.0.2-1/include/mrpt/imgui/CImGuiSceneView.h:24,
                     from /build/mrpt3-release-release-humble-mrpt_imgui-3.0.2-1/src/CImGuiSceneView.cpp:18:
    /nix/store/pjjjv71f9n44k3nqc19dlcbs7bj12m4q-ros-humble-mrpt-opengl-3.0.2-r1/include/mrpt/opengl/opengl_api.h:44:10: fatal error: GL/gl.h: No such file or directory
       44 | #include <GL/gl.h>
          |          ^~~~~~~~~