Missing std::map include in CDUO3DCamera.cpp
The minimal build had the following error.

 error: 'map' in namespace 'std' does not name a template type
 std::map<const mrpt::hwdrivers::TCaptureOptions_DUO3D*, TDUOParams> duo_params;